### ISSUE TITLE
I cannot find the following jar file: digidoc4j-hwcrypto-demo-1.0.7-SNAPSHOT.war

### ISSUE THREAD

**Issue by tynisr** [open-eid/digidoc4j-hwcrypto-demo#2]
I try to run it and follow the instructions in the repository page
I cannot find the following jar file: digidoc4j-hwcrypto-demo-1.0.7-SNAPSHOT.war
Can you guide me where can I find it?

**Comment by nostneji** [comment]
In order to build _digidoc4j-hwcrypto-demo-1.0.7-SNAPSHOT.war_ one must have **Java 8** (jdk1.8.*) and **Maven** installed. Then get code from current repository (_git clone https://github.com/open-eid/digidoc4j-hwcrypto-demo.git_), go into  created directory (where the pom.xml file is) and run Maven (_mvn clear package_). After that you can find war-file in directory **target**.

This is also described in README.md file.
